services:
  - type: web
    name: learning-app-backend
    env: python
    buildCommand: cd back-end-learning-app && chmod +x build.sh && ./build.sh
    startCommand: cd back-end-learning-app && gunicorn dev_core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: learning-app-db
          property: connectionString

databases:
  - name: learning-app-db
    databaseName: learning_app
    user: learning_app_user
    plan: free 