# Render configuration
services:
  - type: web
    name: learning-app-backend
    runtime: python
    buildCommand: cd back-end-learning-app && chmod +x build.sh && ./build.sh
    startCommand: cd back-end-learning-app && gunicorn dev_core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: learning-app-db
          property: connectionString

  - type: web
    name: learning-app-frontend
    runtime: docker
    rootDir: front-end-learning-app
    buildCommand: docker build -t learning-app-frontend .
    startCommand: docker run -p 8080:8080 learning-app-frontend
    envVars:
      - key: API_BE
        value: "learning-app"
      - key: DOMAIN_BE
        value: "https://learning-app-backend-0gfg.onrender.com"
      - key: TURN_ON_SCREEN
        value: "false"
      - key: PORT
        value: "8080"
      - key: PYTHON_VERSION
        value: "3.11.8"

databases:
  - name: learning-app-db
    databaseName: learning_app
    user: learning_app_user
    plan: free 