# Generated by Django 5.0.6 on 2024-05-16 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='instructor',
        ),
    ]
