# Generated by Django 5.0.6 on 2024-05-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_lesson_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extent',
            old_name='extent_name',
            new_name='name',
        ),
    ]
