# Generated by Django 5.0.6 on 2024-05-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_rename_extent_name_extent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extent',
            name='extent_time',
        ),
        migrations.AddField(
            model_name='exercise',
            name='code_solution',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='link_solution',
            field=models.TextField(blank=True, db_index=True, max_length=1000, null=True),
        ),
    ]
