# Generated by Django 5.0.6 on 2024-05-18 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_remove_extent_extent_time_exercise_code_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='detail_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_app.detaillesson'),
        ),
    ]
