# Generated by Django 5.0.6 on 2024-05-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_exercise_detail_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_tagname', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'tagname',
            },
        ),
    ]
