# Generated by Django 5.0.6 on 2024-05-18 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tagname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.tagname'),
        ),
    ]
