# Generated by Django 5.0.6 on 2024-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_exercise_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='tagname',
        ),
        migrations.AddField(
            model_name='exercise',
            name='tagname',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, to='web_app.tagname'),
        ),
    ]
