# Generated by Django 5.0.6 on 2024-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_remove_exercise_tagname_exercise_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tagname',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='exercises', to='web_app.tagname'),
        ),
    ]
