# Generated by Django 5.0.6 on 2024-05-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_exercise_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(max_length=2000),
        ),
    ]
