### User View Set
### All User ( Chỉ duy nhất supperadmin mới có quyền xem tất cả user )
GET http://127.0.0.1:8000/pbkdf2_sha256390000jwfsotswr778gvfsh7wj7fnjacn7hmzwxfbd9cjxpabqqinw0ug2gvi494rrg8m/users/get-user-by-token
Authorization: JWT eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0NjY0NjE1LCJpYXQiOjE3MTQ1NzgxNTUsImp0aSI6IjI4ZGFjYjdhMmYwMzQ5MjNiZDk0MGJjZGQ4MmY3M2E1IiwidXNlcl9pZCI6MTB9.qOLWUtEOVdnAhD_CEZwEmYZxyqWHWC0jTpdRMu6U2xikz_9UDvXzmSm9PFCBZNhLOuiOM3qzGdDPJL-JWaSsPe

### Test TOKEN
# eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5ODIwMDQ0LCJpYXQiOjE3MDk4MTk3NDQsImp0aSI6IjZiMzFkOGI5ZDA2NDRiZGNiNGVmMGJiZmYzODQ0MmFhIiwidXNlcl9pZCI6Mn0.0IGGG8AvZ_0M_bREylK3oWKmNvAbQxJFPFPSbUV3kTDEeb-e0dXlAir-3DkCBf8wT-TP75dhUouN-nGW6g2rew


### Course

GET https://8sync-anhtudev-be.vercel.app/pbkdf2_sha256390000jwfsotswr778gvfsh7wj7fnjacn7hmzwxfbd9cjxpabqqinw0ug2gvi494rrg8m/courses/
# Authorization: JWT eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0NDcxODc2LCJpYXQiOjE3MTQzODU0MTYsImp0aSI6IjU1YTBhNmZkMDdlMjQ1OGI4OGQ0M2IzYTJhOWQ4NGFhIiwidXNlcl9pZCI6MTF9.Kxj0YYcAjQr8uYSTNImuSxKwzzxbbNgpEoghd2CTadeOT2FdkhinaRWM0Z-pg_vHkvBWW2IAoplCw0vazmd4_w


### Lessons
GET https://8sync-anhtudev-be.vercel.app/pbkdf2_sha256390000jwfsotswr778gvfsh7wj7fnjacn7hmzwxfbd9cjxpabqqinw0ug2gvi494rrg8m/lessons/3/list-lesson-of-course/
# Authorization: JWT eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0NDcxODc2LCJpYXQiOjE3MTQzODU0MTYsImp0aSI6IjU1YTBhNmZkMDdlMjQ1OGI4OGQ0M2IzYTJhOWQ4NGFhIiwidXNlcl9pZCI6MTF9.Kxj0YYcAjQr8uYSTNImuSxKwzzxbbNgpEoghd2CTadeOT2FdkhinaRWM0Z-pg_vHkvBWW2IAoplCw0vazmd4_w

### Detail Lessons
GET https://8sync-anhtudev-be.vercel.app/pbkdf2_sha256390000jwfsotswr778gvfsh7wj7fnjacn7hmzwxfbd9cjxpabqqinw0ug2gvi494rrg8m/detail-lessons/1/
# Authorization: JWT eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0NDcxODc2LCJpYXQiOjE3MTQzODU0MTYsImp0aSI6IjU1YTBhNmZkMDdlMjQ1OGI4OGQ0M2IzYTJhOWQ4NGFhIiwidXNlcl9pZCI6MTF9.Kxj0YYcAjQr8uYSTNImuSxKwzzxbbNgpEoghd2CTadeOT2FdkhinaRWM0Z-pg_vHkvBWW2IAoplCw0vazmd4_w

### Get all detaillessons of a lesson
GET https://8sync-anhtudev-be.vercel.app/pbkdf2_sha256390000jwfsotswr778gvfsh7wj7fnjacn7hmzwxfbd9cjxpabqqinw0ug2gvi494rrg8m/detail-lessons/1/list-detaillesson-of-lesson/
